### ISSUE TITLE
Make current tests work

### ISSUE THREAD

**Issue by ralphtheninja** [Level/subleveldown#12]
We need a baseline to start working on. Currently, tests are not passing on node 10.

**Comment by ralphtheninja** [comment]
```
# test _serialize object
/home/travis/build/Level/subleveldown/leveldown.js:105
  this.leveldown.del(concat(this.prefix, key), opts, cb)
                ^
TypeError: Cannot read property 'del' of null
    at SubDown.del (/home/travis/build/Level/subleveldown/leveldown.js:105:17)
    at Test.<anonymous> (/home/travis/build/Level/subleveldown/node_modules/abstract-leveldown/abstract/del-test.js:52:8)
    at Test.bound [as _cb] (/home/travis/build/Level/subleveldown/node_modules/tape/lib/test.js:77:32)
    at Test.run (/home/travis/build/Level/subleveldown/node_modules/tape/lib/test.js:96:10)
    at Test.bound [as run] (/home/travis/build/Level/subleveldown/node_modules/tape/lib/test.js:77:32)
    at Immediate.next (/home/travis/build/Level/subleveldown/node_modules/tape/lib/results.js:71:15)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
npm ERR!0m Test failed.  See above for more details.
```

**Comment by ralphtheninja** [comment]
Some information. `subleveldown` currently depends on `abstract-leveldown@^2.4.1` and the tests _used_ to pass (see old build https://travis-ci.org/Level/subleveldown/builds/88425448).

After some digging it turns out that `abstract-leveldown@2.5.0` (complete diff https://github.com/level/abstract-leveldown/compare/v2.4.1...v2.5.0) broke the tests and it's related to the test for `_serialize*`.

So right now I'm pondering whether to just update to the latest `abstract-leveldown` before doing anything else, or _fixing_ `abstract-leveldown` at `2.4.1`, which I know works, and then start writing tests from there.

@vweevers WDYT?

**Comment by ralphtheninja** [comment]
I've decided to fix `abstract-leveldown` at `2.4.1` for now. Want to get rid of some low hanging fruit first, like updating standard, fixing `new Buffer()` etc.

**Comment by ralphtheninja** [comment]
https://github.com/Level/subleveldown/commit/249abb9c5541cc8f0267ff24cf0657816272534d

**Comment by vweevers** [comment]
I'd choose the same strategy, but that's because I'm not too familiar with the code, though I have used `subleveldown` in the past. So I'd first write more unit tests to learn how it *should* work.
